apiVersion: v2
name: cert-manager
description: Certificate management for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: cert-manager
    version: ~v1.19
    repository: https://charts.jetstack.io
  - name: cert-manager-csi-driver
    version: ~v0.12
    repository: https://charts.jetstack.io
