# Strimzi Kafka Operator for do-nyc3-prod

strimzi-kafka-operator:
  replicas: 1
  watchAnyNamespace: true
  # Skip Linkerd for Strimzi TLS ports (8443: agent, 9090: controller, 9091: internal)
  annotations:
    config.linkerd.io/skip-outbound-ports: "8443,9090,9091"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
