apiVersion: v2
name: istio
description: Istio service mesh with sidecar injection
type: application
version: 0.2.0

dependencies:
  - name: base
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
  - name: cni
    version: ~1.28
    repository: https://istio-release.storage.googleapis.com/charts
