global:
  istioNamespace: istio-system

# Sidecar mode (default profile)
istiod:
  pilot:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

cni:
  cni:
    cniBinDir: /opt/cni/bin
    cniConfDir: /etc/cni/net.d
