apiVersion: v2
name: strimzi-kafka-operator
description: Strimzi Kafka Operator deployment
type: application
version: 1.0.0

dependencies:
  - name: strimzi-kafka-operator
    version: 0.49.1
    repository: oci://quay.io/strimzi-helm
