{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  defaultBackend:
    service:
      name: miniflux
      port:
        number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
{{- end }}
