apiVersion: v2
name: mimir
description: Grafana Mimir with ingest storage using Strimzi Kafka
type: application
version: 1.0.0

dependencies:
  - name: mimir-distributed
    version: 6.0.5
    repository: https://grafana.github.io/helm-charts
