{{- if .Values.onepassword.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  refreshInterval: 3600
  provider:
    onepasswordSDK:
      vault: {{ .Values.onepassword.vault | quote }}
      auth:
        serviceAccountSecretRef:
          name: {{ .Values.onepassword.secretName | default "onepassword-token" }}
          namespace: {{ .Values.onepassword.secretNamespace | default "external-secrets" }}
          key: {{ .Values.onepassword.secretKey | default "token" }}
{{- end }}
