{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-s3-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: S3_BUCKET
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/bucket"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/endpoint"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: S3_SCHEME
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/scheme"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: S3_REGION
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/S3 Configuration/region"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
