apiVersion: v2
name: grafana
description: Grafana with PostgreSQL backend via CloudNativePG
type: application
version: 0.1.0

dependencies:
  - name: grafana
    version: 10.5.3
    repository: https://grafana.github.io/helm-charts
