# trust-manager Bundle to distribute trust anchor to linkerd namespace
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
    - secret:
        name: linkerd-trust-anchor
        key: ca.crt
  target:
    configMap:
      key: ca-bundle.crt
    namespaceSelector:
      matchLabels:
        linkerd.io/is-control-plane: "true"
