{{- if .Values.proxyGroup.enabled }}
# ProxyGroup for HA ingress - shared proxy replicas for multiple Ingress/Service resources
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: {{ .Values.proxyGroup.name }}
spec:
  type: ingress
  replicas: {{ .Values.proxyGroup.replicas }}
  proxyClass: {{ .Values.proxyGroup.proxyClass }}
  tags:
    {{- range .Values.proxyGroup.tags }}
    - {{ . }}
    {{- end }}
{{- end }}
