{{- if .Values.fileBackup.enabled }}
# ExternalSecret for Restic password from 1Password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-restic
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-restic
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.fileBackup.restic.itemName }}/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
# ExternalSecret for S3 credentials for file backup
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-files-s3
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-files-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.fileBackup.s3.itemName }}/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.fileBackup.s3.itemName }}/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
