{{- if .Values.externalSecret.enabled }}
# ExternalSecret for Paperless admin credentials from 1Password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-admin
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.adminItemName }}/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.adminItemName }}/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
# ExternalSecret for Paperless secret key from 1Password
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-secret-key
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ngx-secret-key
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: {{ .Values.externalSecret.secretKeyItemName }}/key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
