apiVersion: v2
name: tempo
description: Grafana Tempo distributed tracing backend
type: application
version: 1.0.0

dependencies:
  - name: tempo-distributed
    version: "~1.60"
    repository: https://grafana.github.io/helm-charts
