{{- if .Values.backup.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-backup-s3
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mlflow-db-backup-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.backup.s3.itemName }}/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: {{ .Values.backup.s3.itemName }}/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
