apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mlflow-db
spec:
  instances: {{ .Values.database.instances }}
  storage:
    size: {{ .Values.database.storage.size }}
  bootstrap:
    initdb:
      database: mlflow
      owner: mlflow
  postgresql:
    parameters:
      shared_buffers: "128MB"
      effective_cache_size: "384MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
  {{- if .Values.backup.enabled }}
  plugins:
    - name: barman-cloud.cloudnative-pg.io
  {{- end }}
