{{- if .Values.artifactStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-artifacts-s3
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mlflow-artifacts-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.artifactStore.itemName }}/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.artifactStore.itemName }}/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
