apiVersion: v2
name: metrics-server
description: Metrics Server for Kubernetes resource metrics
type: application
version: 0.1.0

dependencies:
  - name: metrics-server
    version: ~3.13
    repository: https://kubernetes-sigs.github.io/metrics-server
