# Base values for metrics-server
metrics-server:
  replicas: 1

  # Prometheus metrics scraping
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10250"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "https"

  resources:
    requests:
      cpu: 15m
      memory: 105M
    limits:
      memory: 105M
