apiVersion: v2
name: otel-metrics-push
description: OpenTelemetry Collector for push-based metrics collection
type: application
version: 0.1.0
appVersion: "0.142.0"

dependencies:
  - name: opentelemetry-collector
    version: ~0.142
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
