{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "{{ .Values.externalSecret.itemName }}/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
