apiVersion: v2
name: tailscale-operator
description: Tailscale Kubernetes Operator
type: application
version: 1.0.0

dependencies:
  - name: tailscale-operator
    version: "~1.92"
    repository: "https://pkgs.tailscale.com/helmcharts"
